### ISSUE TITLE
Variables names should be of a consistent language.

### ISSUE THREAD

**Issue by Cin316** [sembsa/CProgressView#1]
In an open source project, it's helpful for a variables to be in the same language (usually English).  In [CProgressView](https://github.com/sembsa/CProgressView/blob/master/CProgressView/CProgressView.swift), both Polish and English variable names are used.

The easiast fix would be to change the name of the variable "wynik" to "result" on lines 16-17.

I can make this fix if you want, and submit it as a pull request.

**Comment by sembsa** [comment]
Hello, thanks for review. I fix this today :) and add MIT Licence is ok ?

**Comment by Cin316** [comment]
Yeah.  I think the MIT License would be great.

## 

Nicholas

**Comment by Cin316** [comment]
The issue has been fixed with commit fcdc6ad85d5b2121dc40519957f356ace9925a0b .  Because the problem is fixed, I am closing the issue.
