### ISSUE TITLE
[Suggesstion] Change CProgressView to be a subclass of UIView

### ISSUE THREAD

**Issue by Cin316** [sembsa/CProgressView#4]
Normally custom UIViews are subclasses of UIView, instead of a separate class which manages a view.  This would also allow the CProgressView to be used in the Interface Builder.

**Comment by sembsa** [comment]
Hello, i'm update :) If I ask you about the update description because I have poor English. If you do not give advice, write.

**Comment by Cin316** [comment]
@sembsa I'm sorry, but I don't understand this.  You can speak English much better than I can speak Polish, so you don't need to say sorry (apologize) for your bad English.

I can't understand what you are trying to say in the last comment.  Can you try to rephrase it (reword it/change the way it is written/say it in a different way)?  I would like to help.

**Comment by Cin316** [comment]
@sembsa Also, the changes you made look really good.  I think this solves the issue, and you can probably close this issue.
